services:
  gmp-cpu:
    build:
      context: .
      dockerfile: Dockerfile
    image: gmp-image-cpu
    container_name: gmp-container-cpu
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true
