version: '3.8'

services:
  gmp-gpu:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    image: gmp-image-gpu
    container_name: gmp-container-gpu
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu] 