services:
  gmp-featurizer-cpu:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gmp-featurizer-cpu
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true
