version: '3.8'

services:
  gmp-featurizer-gpu:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    container_name: gmp-featurizer-gpu-dev
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu] 